on:
  push:
  pull_request:

name: "Proselint"

jobs:
  proselint:
    name: Run Proselint
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: o2buzzle/action-proselint@main
    
